# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f50ce1f8171205898284b29d7a93e21bf75c024ae2d79235e6c1b3ac475c8393c4c63c80a19261c0bc8ef941e92bf810216c18fa8e3eb36e3f4ea755c493bc98

test:
  secret_key_base: 7e8c51a585a00746b2e88bd5eb3340dfdff079f90a8d51363bf0bbc38366e0a87a6777c47118a51f959f4911137d4b4aad48073733cbfcaf73170a4d6aff276d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
